Warning:
    3:
        command: kick
    4:
        command: kick
    5:
        command: tempban
        duration: 3 day
    6:
        command: tempban
        duration: 7 day
    7:
        command: ban